version: '3.7'

services:
  cfg0:
    hostname: ${CFG_HOST_0}
    container_name: cfg0
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--configsvr", "--replSet", "${CFG_RS}"]
    env_file:
      - .env
    volumes:
      - './int-config-server.sh:/int-config-server.sh'
    networks:
      - mongo_sharded_cluster
    
  cfg1:
    hostname: ${CFG_HOST_1}
    container_name: cfg1
    image: mongo
    restart: always
    env_file:
      - .env
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--configsvr", "--replSet", "${CFG_RS}"]
    networks:
      - mongo_sharded_cluster

  cfg2:
    hostname: ${CFG_HOST_2}
    container_name: cfg2
    image: mongo
    restart: always
    env_file:
      - .env
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--configsvr", "--replSet", "${CFG_RS}"]
    networks:
      - mongo_sharded_cluster

networks:
  mongo_sharded_cluster: {}

