version: '3.7'

services:
  mongo0:
    hostname: mongo0-${MONGO_REPLICA_SET}
    container_name: mongo0-${MONGO_REPLICA_SET}
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}" ]
    env_file:
      - .env

  mongo1:
    hostname: mongo1-${MONGO_REPLICA_SET}
    container_name: mongo1-${MONGO_REPLICA_SET}
    image: mongo
    restart: always
    env_file:
      - .env
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}" ]

  mongo2:
    hostname: mongo2-${MONGO_REPLICA_SET}
    container_name: mongo2-${MONGO_REPLICA_SET}
    image: mongo
    restart: always
    env_file:
      - .env
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}" ]
